--- #YAML:1.0
name:               HTML-FormatExternal
version:            16
abstract:           HTML to text formatting using external programs.
author:
    - Kevin Ryde <user42@zip.com.au>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Encode:        0
    File::Temp:    0
    perl:          5.006
    Perl6::Slurp:  0
    Test::More:    0
resources:
    homepage:  http://user42.tuxfamily.org/html-formatexternal/index.html
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
        - devel
        - examples
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
optional_features:
    maximum_devel:
        description:  Stuff used variously for development.
        requires:
            I18N::Langinfo:     0
            Module::Load:       0
            Pod::Simple::HTML:  0
    maximum_tests:
        description:  Have "make test" do as much as possible.
        requires:
            HTML::TreeBuilder:   0
            Parse::CPAN::Meta:   0
            Test::DistManifest:  0
            Test::NoWarnings:    0
            Test::Pod:           1.00
            Test::Synopsis:      0
            Test::YAML::Meta:    0.13
            YAML:                0
            YAML::Syck:          0
            YAML::Tiny:          0
            YAML::XS:            0
