--- #YAML:1.0
name:                HTML-FormatExternal
version:             14
abstract:            HTML to text formatting using external programs.
license:             gpl
author:              
    - Kevin Ryde <user42@zip.com.au>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Temp:                    0
    Perl6::Slurp:                  0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
optional_features:
    maximum_tests:
        description: Have "make test" do as much as possible.
        requires:
            Test::Pod: 1.00
no_index:
    directory:
        - devel
resources:
    homepage: http://www.geocities.com/user42_kevin/html-formatexternal/index.html
    license: http://www.gnu.org/licenses/#GPL
