--- #YAML:1.0
name:               HTML-FormatExternal
version:            22
abstract:           HTML to text formatting using external programs.
author:
    - Kevin Ryde <user42@zip.com.au>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Encode:      0
    File::Spec:  0.8
    File::Temp:  0.18
    IPC::Run:    0
    perl:        5.006
    Test::More:  0
    URI::file:   0.08
resources:
    homepage:  http://user42.tuxfamily.org/html-formatexternal/index.html
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
        - devel
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
optional_features:
    maximum_tests:
        description:  Have "make test" do as much as possible.
        requires:
            HTML::TreeBuilder:  0
